### ISSUE TITLE
CA_pod_discussions

### ISSUE THREAD

**Issue by rainersachs** [rainersachs/CA.2019.plus#1]
Soon will become preferred method of presenting information and debating approaches for CA pod matters

**Comment by rainersachs** [comment]
To Peter from RKS.

1. If you have time, please make a version of the code that runs everything including monte carlo and ggplot. Put it on github. Rainersachs/CA.2019.plus. I will take it off github, put it in my sandbox, and start using it to make figs and tables for the paper.

2. ggplot() has problems from my point of view when I am choosing and making figures. For example, none of the figures you sent me recently had any straight lines at all. Instead the used very thin rectangles filled in with some soft colors. I cannot adequately tweak figures within Adobe Illustrator if they use such rectangles – grabbing and changing a rectangle becomes too difficult. Is there a command which tells ggplot to draw lines as lines? If not I will have to use plot( ) for all final figures for the paper. There are other, similar problems.

3. When choosing figures for the paper I will need a lot of flexibility. Ideal for me would be to have a separate plots.R script and within it completely autonomous chunks, 1 chunk for each figure. The input to the chunks would be the same for all chunks and not constrain the chunk in any way. Each chunk would contain all its plotting command and not anything else. No chunk would ever know the other chunks exist. After the figures are all decided, you would know exactly what functionality we use and could write an R function that helps a user not type in redundant information.

**Comment by rainersachs** [comment]
Hi Peter and Sherry!
1.	This GitHub "issue" entry mainly concerns the agenda for our 9/11/2019 meeting, but sme smaller items are also included. Thanks again for joining URAP.
2.	We have the makings of a potent CA team and good pod paper. Sadly, each of you will probably leave by next June or earlier. So let's try to get a fast start if we can. That said, there is no real reason to hurry so we can afford taking time to try to make sure we are not going to regret being over-hasty.
3.	I suggest our weekly meetings should have the following as default pattern. They will be at the Strada, weather permitting. Sherry will come shortly after 11, Peter shortly after 12. If at all possible Sherry will stay an extra 15 minutes (tentative default) or Peter will come early, at 11:45, so that we 15 minutes to discuss the inevitable issues that will need all three of us to handle. I would strongly prefer a schedule that includes that 15 3-way bit, in my office whenever your being near Evans if that is the best way to get in the 15 minutes, to two disjoint 2-way meetings.
4.	I think helping Sherry direct her efforts during the next 5 weeks will be fairly straightforward. She still needs a lot of reading and of mathematical calculations to get an adequate overview of the coding needs and purposes. With luck a full running (though perhaps still pretty ugly) code will be ready; once she gets her hands on a running code she will, I expect, be quite capable of designing her own weekly assignments by herself with no more help than a few comments from Peter and me. Peter OTOH has a lot on his plate and organizing his efforts may take him and me to think carefully.
5.	Peter:
5.1.	Under all circumstances you will probably, perhaps with Sherry's help and some general guidelines from me, need to do a hard recoding job by January to make the code fit for other people to use and for URAP to use next year. The following applies more to what to do in the next  30 days or so.
5.2.	You could choose to concentrate on getting a full suite with plot-capabilities running; alternately you could choose to be more careful. The first would help Sherry and me get a fast start, help Kulunu continue writing, help make Megumi happy, and help timely uncovery of gaps in the pod's paper's logic. The second would decrease the distinctly unpleasant possibility of needing to spend most of October undoing the results of having spent most of September implementing a flawed approach. If time permits could you decide for yourself how best to choose between a doing a quick, convenient, possibly over-optimistic September job and a slow, near fail-safe September job. If we can agree on this aspect Wednesday that will simplify things.
5.3.	As regards the issues about plot colors, dotted lines, etc. thanks again for your careful summary. If there is anything you don't understand or don't agree with in my detailed reply, please make a note to bring it up at our meeting.
5.4.	As regards the frustrating issue of some 1-ion experiment data sent by Megumi having the same Z and same Mev/u as other rows of the big 1-ion master .xlsx used to prepare the code's input 1-ion .csv. it seems obvious to me there must be some way within R or Excel to ensure proper processing. I think we need to find that way rather than putting ourselves in the position of refusing to listen to what Nature is telling us about herself because her phrasing is not to our liking. LETs are approximate. It could easily be that in any particular experiment all LETs are somewhat smaller than most other experiments – for example that is exactly what would occur if there happened to be extra matter between beam injection and HG in that particular experiment (maybe for another experiment by some completely different group that needs intentionally added matter and is so nearly simultaneous that there is not time to add or remove the matter between experiments. Maybe due to some minor glitch deemed too minor to abort the entire experiment, etc.)
5.5.	Please also come with a long agenda of your own and let's try to zip through everything, catch errors in each other's agenda, and get caught up so that going forward we can think mostly about the science involved and not be plagued by bookkeeping stuff.

**Comment by rainersachs** [comment]
Hi Peter!
Thanks for uploading the files! Looks like a big step forward. Your agenda looks excellent and you should definitely not let your exams suffer - we need not hurry.
Here are some questions. I put them in this issue because that way I have a **dated** record for myself of what was puzzling me.
1. Why are the V1 files from 2 months ago present?? Can they all be deleted, including raw data ordered.csv? If not, can they be put in a subfolder clearly labelled and with "obsolescent" in the lable? Or are they still current but as a different branch?
Let's really try to keep the naming in this repository self explanatory, short, and informative. Let's really try to keep the files to an absolute minimum, especially in the top directory/folder. Let's try to always have the repository cleaned up after each push, with anything that can be misinterpreted explained in this "issues" file. Otherwise I will get confused, download the wrong names or wrong files, and then be stuck with a project in my home sandbox which is a mess.
2. I tried downloading CSV_late_July.csv, DataTable.R, and synergy.R. I thought they might run.  But synergy.R tries to source synergy functions.R and I cannot find synergy functions.R anywhere. Was that file inadvertently omitted? 
3. The label CSV Late July .csv file needs improvement. "CSV" is redundant. There is no way to tell that this is a 1-ion .csv nor will a newbie 6 months from now be able to tell July of which year is referred to. "1-ion9.1.2019.csv" would be more self explanatory.
4. There is a comprehensive file containing all the other files near the top of the main folder/directory. What is its purpose? I don't think the user is supposed to download it but in that case how is user supposed to know what to do with it?
5. I put some files where I wanted to remember what they were into a subfolder/directory. Unfortunately I labelled the directory badly and now for some reason I can no longer change the name. Sorry about that.
best, ray

**Comment by rainersachs** [comment]
Peter and Sherry: do you get notifications  when, as here, I comment on this CA_pod_discussions#1 "issue".
Hi sherry! I just tried to set notifications on for your email. Did it work?
Sherry: If you have questions or comments this is a good place for them. However, for the first half of the semester, please do not push changes to the actual code rather than just this "issue". Give them to Peter or me and let us push them for you. Thanks.

**Comment by rainersachs** [comment]
Here is the latest version of this semester's class paper

[master_PLoSbiology9.16.2019.pdf](https://github.com/rainersachs/CA.2019.plus/files/3618100/master_PLoSbiology9.16.2019.pdf)

**Comment by rainersachs** [comment]
still no notification sherry?

**Comment by rainersachs** [comment]
I wanted to leave a .pdf here but until I am sure Sherry can get notified if she wants that would not work. So I attached it in an email instead just now, to the possible detriment of future CA podders.  (-:>>

**Comment by yshi2016** [comment]
I just found out that I can subscribe to this issue! I think I might be able to receive notification now!:)

**Comment by rainersachs** [comment]
yes sherry i think everything is working now as regards github! thanks.
please do not push any actual code to this repository till we  have tested it a bit more. for the time being just use this issue.  In this issue always select the green "comment", not the red "close and comment".

**Comment by peterwangshichun** [comment]
### **[10/2/2019] Meeting Recap**
**Peter's comments on the draft of intro of the paper, by keyword:**
1. _"low doses"_ Bullet point 1.2.1: "Model Used". Q: **What specific range does it refer to?**
Discussion: (a): The answer depends on the endpoint: different endpoints and different questions in mind will have very different expectation on dose levels. For example, cell deaths will need higher dose levels than any mutation. (b): The answer also depends on the ion: low dose of HZEs are "higher" than low dose of SLIs. (c): The answer also depends on who's reading. Some people are expecting 0.0001 - 0.01 cGy whereas some others are expecting anything less than 1 cGy. In conclusion, as long as the reader realizes it's not anything above 50cGy, we don't need to, and cannot, specify exactly what this term means, especially in the introduction. But we can make it a little more descriptive at least by mentioning the intricacy/complexity of this issue.

2. _"regression"_ Bullet point 1.2.1: "Model used". Comment: **It looks like linear regression.**
Discussion: By default, Peter thinks that when the phrase "regression on the data" is used without specifying the type of regression, it is assumed to be linear. However, our models are not linear, which could cause some confusion. Peter thinks it's best to add something, maybe in the parentheses, along the lines of "non-linear in our case", "nlsLM", "non-linear regression on the data".

3. _"very curvilinear"_ Bullet point 1.5: "More on NTE". Q: **What is the definition of curvilinear and how curvilinear is "very" curvilinear?**
Discussion: At low doses, assuming we know what it means, the earliest theory and estimation was based on LNT (Linear-non-threshold), a linear line with positive slope through the origin. Then the "convex school of thoughts" argued extreme convexity and lower than estimated at low dose levels. Then Sachs used new data from Harvard to argue for the new "concave school of thoughts" at low dose levels, showing even higher than expected damage at low doses. Both are considered curvilinear, and in our case the NTE-also model is concave, TE-only models are convex. Even in the TE-only model, we can easily show that SEA is not a good idea.

**Cairo problem: exporting ".eps" files from ggplot2.**
1. _Problem on Sherry's computer_: There were error messages when exporting the graphs, saying that cairo does not work properly. This is probably due to the Operating System (Mac for Sherry) since it did not show up on Peter's computer (Windows). Sherry will, hopefully, find a cure to make Cairo work on her current version of mac OS.
2. _Problem on Sachs' computer_: Since there were no error messages that came up, according to the document of error messages from Sachs, Peter thinks the graph was exported as eps, but to the wrong location. Try the following: close any RStudio panels, and open Graph.R directly in the subfolder. The default path will be the same location as Graph.R file. Sourcing previous files won't change this. After running the code sequentially, try to run the current ggsave line again (which is using Cairo). Let Peter know if Sachs sees the exported eps files in the same folder.

**Style of R codes: Research Version vs Presentation Version**
Peter should talk to Edward. Edward has agreed to "modularize" Peter's presentation version of the code to make it more flexible, by tearing down high-level functions into chunks and converting ggplots back to basic, uglier in Peter's opinion :) , base package plot lines to add more flexibility. Sherry will probably work with Edward on this?

**SLI Model Comparison**
Currently we do not have a thorough model selection section for SLI models (4 of them in total: linear, quadratic, and 2 exponential models). Peter will implement AIC, BIC, and CV for this section. 

**Confusion Caused by Obsolete Models**
Problem is two-fold. 1: Some obsolete models are in too many parts of the program. Most of them should be killed by Model selection. 2: The naming is confusing. Sherry will clean this up this semester.

**Peter Forgot to Mention This in the Meeting**
Are we having a Prof. Sachs + his apprentice lunch/coffee session this semester? Since there are new members of URAP this year, maybe we should do that iHouse thing again.

The last bullet point is obviously the most important of all. Food is life. Free food is even better! 👍 

Best,
Peter

**Comment by rainersachs** [comment]
Yes! we are having an Ihouse great Hall all the Lox, Bagels, orange-juice, coffee, potatoes, raspberries and whipped cream deserts, etc. you can eat brunch paid for by URAP. It will probably be on the first Saturday of dead week, just after classes stop, starting at about 11:30. As soon as I have time I will send an email to all fall 2019 URAPPERs and all former URAP students that are likely to be in town, telling them to save the date and asking for a volunteer to organize the details.

**Comment by rainersachs** [comment]
On Wed, Oct 2, 2019 at 9:13 PM Yiwen Shi <yshi2016@berkeley.edu> wrote:Hello Peter and Professor Sachs,Yes I got the notification from Github. And I just did some research on the cairo thing, I installed a software called XQuartz but still it said "fail to load Cairo". However, after I removed the device parameter (both remove "eps" and cairo_ps), there is a plot generated, attached below.  (is there a way I can upload pic on Github?)Is it what the plot supposed to look like?e research on the cairo thing, I installed a software called XQuartz but still it said "fail to load Cairo". However, after I removed the device parameter (both remove "eps" and cairo_ps), there is a plot generated, attached below.  (is there a way I can upload pic on Github?)Is it what the plot supposed to look like?Thank you!Best,Sherry

Thanks Sherry! I get a .eps file and can manipulate it within Illustrator. Excellent! Peter will have to check with his computer but it looks like the whole Mac problem is solved.

You can put .eps files on GitHub as is. Make a third directory that is dedicated to .eps files within the branch master directory. Inside the new directory make 3 subdirectories: From Sherry;  From Peter; From Ray. Each of us can push to our own .eps subdirectory however we want but not push to the other 2 .eps subdirectories. Every body can download anything from the repository. If you run into trouble ask Gracie for help

**Comment by rainersachs** [comment]
Meetings are in my office this coming week NOT Strada. Default is peter at 2 and Sherry at 2:15 but if Peter wants to change the time to 1:15 or either of you needs to cancel, just let me know.
Peter: I started to check if your solution to my graphing problem works, but it looks like I may not have time before the Wednesday meeting.
Best, Ray

**Comment by peterwangshichun** [comment]
It looks like tomorrow Berkeley will shut down as PG&E plans to temporarily shut off power for Wednesday and Thursday as a precaution due to "high wildfire risk". Let me know if we are still meeting on campus. Not sure what's gonna be open tomorrow.

**Comment by rainersachs** [comment]
Hi Peter and Sherry!
1. Sherry's figure is just what I need. It does not have a ribbon (Sherry emailed that it did but I assume that was only a slip of the pen?). Later we may want the same Fig. but with a narrow ribbon for IEA (no SEA ribbon will ever be needed).
2. As discussed in emails I suspect you 2 do not want to write an abstract for HRP 2020 by next wednesday, but let me know ASAP if you decide to.
3. Default is meeting in my office (not the Strada) next Wed. Peter at 1 or 2 and Sherry a bit after 2. However I have a minor oral surgery tuesday afternoon and will be a bit under the weather,
4. To reiterate, thanks for having already put in so much work we were able to Hada's request within 8 hours and are freed up for other stuff like working on grad school applications.

**Comment by peterwangshichun** [comment]
Hi Professor,

1. Let me know if you need another plot with ribbons. Sorry I was not available yesterday.
2. I won't be here in the US during the HRP conference, so I probably won't write the abstract for it.
3. See you next Wednesday. I'll probably come at 1PM.

**Comment by rainersachs** [comment]
Sometime, at your leisure,  send me one with a yellow IEA ribbon having
roughly the same height and length as Sherry's. I will use them both.
thanks for letting me know about the abstract.
Sherry: let me know if you got this. best to both of you, Ray

**Comment by peterwangshichun** [comment]
Hi Sherry: can you also send me the plot you sent Professor Sachs so I know what mixture you used? And also in the future it would be helpful if you cc me or the Professor when you are emailing to the other person.

**Comment by rainersachs** [comment]
Hi Peter: Thanks for the new figures. They look excellent at first glance. 
1. This December, but not sooner I will a Third figure of the same data but much simpler: only the SEA and IEA NTE and TE curves (4 curves in all) and a yellow ribbon for the NTE IEA curve. No empirical points at all. We need to explain why our results are different from Megumi's results on the same poster (she uses SEA and uses different 1-ion models) and the figure is needed for that.
2. I swear I was planning to work on CA graphs.R but two crises arrived yesterday. One, now solved in principle, concerns minor mistakes in the mouse-pod's 1-ion data due to combining old Bevalac data from the the 20th century with more recent NSRL data; there is an enormous clean up now needed before the mouse pod can presubmit to LSSR. The other is a major problem with Polly and Ellie's HRP IWS 2020. See you next Wed!
results on the HG 6-ion mixture. Sorry!

**Comment by rainersachs** [comment]
Hi Peter and Sherry:
I tried Peter's cure for my mislocated plots but only got a WordPad result, not any running code that produces figures in a form where they can be made into .eps files.  I suspect the problem has to do with a different bug in the method I always encountered when saving from GitHub but had learned to circumvent, namely my .R files always appear in my downloads folder as .R files but when I move them to my project in RStudio and look at them within RStudio they are actually files of the form foo.R.txt (and when saving them from GitHub I correspondingly have only 2 options .txt files and all files, both of which always give me foo.R.txt.  My circumvention was always to use the rename function of RStudio to rename the files within RStudio by deleting the extra .txt. Of course I had the same problem when following Peter's instructions. So I tried the same solution, then closed RStudio, then double clicked on Graphs.R. All I got was a wordpad file (a mild improvement on the notepad file I get when failing to delete the extra .txt), not a running file. Evidently my manipulations made Graphs.R forget it was an R file. 
     So I have temporarily given up on getting .eps figures within my sandboxes and hereby remind myself to delete the extra sandboxes and downloads I produced while trying.
    I will see you two in my office wed.  I will be a little groggy and maybe mumbling due to mild dental surgery tuesday but we have lots to discuss. let me know soonest if either of you has to cancel wed. Other wise I look forward to seeing and hearing you, though perhaps being only able to mumble! I have a suggested hard extra project for Sherry in mind in the unlikely case she has too little to do.

My office, not Strada. best, Ray

**Comment by rainersachs** [comment]
[Yelesetal.2017.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735865/Yelesetal.2017.pdf)
[Bakkenistetal.2019.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735866/Bakkenistetal.2019.pdf)
[Karthiketal.2019.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735867/Karthiketal.2019.pdf)
[Lepleuxetal.2019.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735868/Lepleuxetal.2019.pdf)
[Noda.2018.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735869/Noda.2018.pdf)
[Tuetal.2019.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735870/Tuetal.2019.pdf)
[Vasumathyetal.2019.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735871/Vasumathyetal.2019.pdf)
[Yahyapouretal.2018.pdf](https://github.com/rainersachs/CA.2019.plus/files/3735872/Yahyapouretal.2018.pdf)
Hi Sherry! see you at 2 my office today!
I have a literature search sub-project to discuss with you today, though I understand from Peter that you are still studying the code and that remains your assignment for now.  But to prepare for literature sub-project please make a folder containing the 8 .pdf files uploaded here, plus all papers that are used when we reference NTE in either the CA pod paper Introduction draft or the mouse pod LSSR paper. Thanks

**Comment by yshi2016** [comment]
Hi Professor Sachs! 
Should I make a folder locally or within this github? Shall I pull and push again with the new folder?
See you at 2!
Best,
Sherry
No make a folder in your computer. Thanks!

**Comment by yshi2016** [comment]
Since I modified my Graphs.R, I am having a merge conflict when pulling, should i revert to Cairo code and pull again? 
     Sherry, Are you sure the dim type is not some GitHub trying to suggest text to you so you have a template on what to type next?

**Comment by rainersachs** [comment]
Hi Peter and Sherry! Thanks for very useful meetings yesterday. Based on the meetings I suggest the following priorities and plans
1. Getting me, for my own sandbox only (never for anyone outside URAP to look at) a functional plot() rather than ggplot() version of the CA program suite, with each plot completely localized within its own chunk and completely independent of all other chunks, now has the highest priority. This "uglySachs" suite will be very different from the present CA code, which seems to be fully functional, just needs to be gradually tweaked to make things easier for readers of the eventual CA paper, will always remain the only code in the GitHub main branch main folder (i.e. main branch main directory), and will probably remain the only code anywhere in this repository.
2. uglySachs is time sensitive. Hopefully for the rest of this semester, Peter, Sherry, and (importantly) Edward all have at least 1 or 2 hours per week to spend on uglySachs. Sherry may well have considerably more than that. The three of you will be able to write uglySachs this semester with that amount of workload. In a worst case scenario for Sachs, none of you will be available next semester. If uglySachs is ready by then Sachs will be able to go it alone or with the help of a newly recruited URAP programmer. Otherwise the paper may be delayed indefinitely.
3. As an aside, Sachs, with Kulunu's help, has to be the one writing the paper drafts. Sherry and Peter would at present find that too hard.
4. The template for the uglySachs suite has to be the mouse HG suite from my own sandbox. I will send that to Peter and Sherry today by email (to avoid cluttering up this GitHub repository). The priority assignment for the coming week is for Sherry and Peter to make sandbox RStudio projects, make sure the code runs and gives plots in the RStudio plots window, and record any questions they have for discussion with Sachs in this gitHub issue#1 box or in next week's meetings. If there is extra time Peter and Sherry should start to code uglySachs, as follows.
5. Edward knows the mouse HG suite from my sandbox that I am sending you by email thoroughly. He knows in general what the CA pod has been doing, but not much about the most recent specific developments. Peter and Sherry, when coding uglySachs, should place heavy emphasis on making it clear and convenient for Edward. I am guessing that if uglySachs is prepared well for him to look at and he spends a day or less on it, he will be able to make it run except for minor tweaks.
6. In preparing uglySachs for Edward and for Sachs, you can:
     (a) use ggplot code rather than plot code, but you should comment it out ggplot code before trying to run uglySachs. Sachs can translate ggplot into plot easily if each figure is isolated in its own chunk. If you want to test whether a specific chunk is alive, put in the following command: plot(c(1,2), c(5,3)). That should show in the RStudio window as points with (x,y) coordinates (1,5) and (2,3) so the slope if a connecting straight line were drawn would be -2.
     (b) give just 4 plot chunks (not 10 or 15 as in the code I am sending by email). 1 chunk should be any 1-ion plot you want with both narrow and wide ribbons; one chunk should have IEA and SEA DERs for some mixture (other than the 6-ion mixture for Megumi's HRP IWS poster) but no ribbons; one chunk should have IEA and the narrow ribbon for a third mixture (e.g. a 2-ion one). The final chunk should kill two birds with one stone: have the simplified 6-ion plot with only SEA line, IEA line IEA narrow ribbon and the three mixture data points with their error bars. This is needed for the poster and also will give me a fourth example. From the four examples I will be able to construct new plot chunks whenever I need them.
7. I am adding a .pdf version of this set of instructions to this issue#1 comment box so you can download them if you want. I will correct this box off and on as we uncover improved instructions. Please record your comments about uglySachs in subsequent boxes of this issue so future newbies have a record of what we did. 
8. Thanks as always for your essential assistance and pleasing cooperation! Best, but in haste, uglyRay
[PeterAndSherry.pdf](https://github.com/rainersachs/CA.2019.plus/files/3741235/PeterAndSherry.pdf)

**Comment by yshi2016** [comment]
Hello Professor Sachs!
Thank you for the instructions. So for now, should I download the files you sent me, put them in a folder, and try to see if the whole thing will source in my laptop?
Sherry

**Comment by yshi2016** [comment]
And come up with a version related to CA data with the same code structure?

**Comment by rainersachs** [comment]
Hi Sherry and Peter.
Meetings this Wed are in my office, not the Strada; usual times.
I am still very busy working on submission of the mouse pod's LSSR paper. If you two have as much useful URAP work as you have time for I would like to leave everything as regards assignments and agendas for our meetings basically up to you -- you seem to be doing fine on your own! Contact me if: (a) you need to cancel this week; (b) you want my suggestions before Wed. as regards any specific questions you have; or (c) you would like me to devise additional sub-topics than the ones we already have for the last half of the semester. best, ray

**Comment by rainersachs** [comment]
Hi Peter and Sherry
My PG&E power outage map for Tuesday includes my home and UCB campus among its power off areas. In view of the possible bad air hazard and the fact that PG&E may cut power to one or more of us, let's make the default this Wednesday meeting, by phone (510-658-5790) and/or email, at the usual times.  If you can't reach me it means my power is off and I have to deal with that anyway instead of meeting. If you can reach me and you want to cancel that will also make that easier.
     If Tuesday brings unexpected good news on the weather, we can still meet by telephone and email, rather than trying for rearrangements that might be wrong if the weather worsens Tuesday night.
     Assuming no power outage I will submit the LSSR paper before Wed. night and thus finally have time to try out the new modular version of the CA code.

**Comment by rainersachs** [comment]
Hi Peter!
this week can you call me at the usual time to discuss your grad school applications?
I am able to run your new version of the code! I put in a toy plot, ( (1:10)^2 as a function of d=1:10) and it ran fine.
what is the simplest of your examples in Graphs.R. I want to translate that simplest one from ggplot to plot and try to run it. Does Graphs.R have any example as simple as a single-HZE ion DER with its narrow yellow ribbon?

Hi Sherry! fine about taking this week off to catch up. But please call me briefly Wed at 2:30 (If PGE shuts off my power you won't be able to reach me). I want to ask some questions about the request in your last email.

thanks to both of you. I think I can, if necessary, do the rest of the coding during the phase when we are deciding what plots to put in the paper. that is really good news, if true.

**Comment by yshi2016** [comment]
Hi Professor Sachs! 
I will call you at 2:30 tomorrow! Thank you very much! :)
Sherry
